= Lone Star Masonry (Special Guest: Robert Marshall)
:published_at: 2017-07-13

== _Pre-Recorded: Sam Obiturary_

Details: http://www.greenwoodfuneralhomes.com/obituaries/Sam-Levisee/#!/Obituary

== _Intro Music w/ Disclaimer_

== Host and Guest Introductions

Remember to rattle off your Blue Lodge titles, y'all.

* Rhit
* Grant
* Gabe
** "and we have a special guest today..."
* Robert

== _Pre-Recorded: Masonic News for Week of Tomorrow's Release_

=== Temple
* We had a great stated meeting this Monday. We had 46 or so brothers attend, including a sizable contingent from Oklahoma. We would like to extend our special thanks to them and an extra special thanks to Right Worshipful Deputy Grand Master Corky Grigsby the pleasure of hosting him! Our special congratulations to Brother Namon Kouri, worshipful master of Frederick Lodge #249 under the jurisdiction of the Grand Lodge of Oklahoma. Brother Kouri's mother lodge is Fort Worth Lodge, and although he had to relocate to Oklahoma, he was able to come down for his 25-year pin! So once again, congrats Brother Kouri. In light of Brother Sam Levisee's passing onward and upward into the pearly gates, instead of Masonic education that night, each one of us that knew Sam stood up and told a story about him. It was beautiful. Not a dry eye in the place.

=== Local

=== State

* https://lonestarmason.wordpress.com/2017/07/07/masonic-improvement-the-chamber-of-refraction/[Go check out the blog Lone Star Mason by Brother Justin Jones.] I've been on a real kick of reading different blog posts by "local" guys, so to speak, ever since Brother Lance Kennedy wrote his _10 Propositions for Texas Freemasonry_. It seems like there's been an increase in writing, sharing, and reading masonic blog posts since that. Anyway, Brother Justin put up a great piece on the Lone Star Mason blog called _The Chamber of Refraction_, in which he talks about some of the common problems he's encountered in the anteroom in which candidates are prepared for degrees. I highly recommend it. Check Brother Justin out at lonestarmason.wordpress.com.

=== National

* https://www.reddit.com/r/freemasonry/comments/6mr4ul/posted_on_brother_andrew_hammers_facebook_page/?st=j51azesu&sh=accae4b7[Alexandria-Washington Lodge #22, Grand Lodge of Virginia, AF&AM] - Brother Andrew Hammer, former Worshipful Master of Alexandria-Washington, has demitted from his lodge, and as such, is no longer a Mason under the jurisdiction of the Grand Lodge of Virginia, and is not under charges or on suspension there. He's still a Mason in a few other jurisdictions, so if you were planning on having him come speak at your lodge, you'll still be fine. His situation with his Grand Lodge has been resolved, and we wish Brother Hammer the best of luck in his future endeavors. 

* http://www.jsonline.com/story/news/crime/2017/07/03/lawyers-seek-release-man-charged-16-months-ago-plotting-foiled-machine-gun-attack-milwaukee/424399001/[Milwaukee, WI] - there's some more news on the attempted attack on the Scottish Rite Temple in Milwaukee. About a year and a half ago, this guy called Samy Hamzeh was arrested by the FBI on two counts of possessing an illegally-acquired fully-automatic firearm and one count of possessing an illegally-acquired suppressor. He's looking at up to 30 years in prison for this. However, now it's come out that he bought those from undercover FBI agents, and interestingly enough, he was talked into preparing the attack by FBI informants. One of the informants, called "Mike," is the one who specifically introduced Masons into the equation, telling Hamzeh that Masons were affiliated with ISIS and that Masons were the enemy of Islam and ate human hearts. Now, Hamzeh and his lawyers are pushing for a case of entrapment. Supposedly, the audio transcripts of the phone calls reveal that for a long time, Hamzeh actually repeatedly rejected the ideas that were being pushed on to him. Obviously, this case is still in development, and we'll update y'all as we learn more.

* http://www.cincinnati.com/story/news/2017/07/07/anti-trump-graffiti-suspect-indicted/457103001/[Colerain Township, OH] - a man is being held on bail after being arrested for two counts of misdemeanor criminal damaging. This guy, Avery Collins, graffittied buildings and cars at two businessess with anti-Trump and anti-Masonic graffiti. He wrote things like "Kill Free Masons," "Kill Freemasons ASAP," and "Black Lifes matter Bitches Burn Trump with all Crackers." Pretty scary stuff - take care out there, brothers. By the way, to the conspiracy theorists and/or anyone wondering: I'd like to point out that Masons aren't affiliated with any one politician, or any one party. 

=== International

== Listener/Discussion Questions

* Quick question with quick answer: I was told if you have tattoos you can't be a mason. True or nay?
* Discussion question: Does your lodge have any resident ghosts?

== Episode Content

Special Guest: Robert Marshall

=== Standard Guest Questions

* Can you tell us about yourself in a nutshell?
* When did you join the Craft?
* What inspired you to join?
* Which lodge did you join at first, and what drew you to them?
* What do you think of your experience while going through the degrees?
* Can you tell us a little bit about your lodge?
** History
** Stated Meeting dates/times
** Floor School dates/times
* What officer positions have you held in the past?
* What is your favorite aspect of Masonry, and why?
* What do you think are the strengths and weaknesses of Masonry in Texas? (or "your state" if guest is a Mason outside of TX)
* How do you see the overall state of Masonry in Texas? (or "your state" if guest is a Mason outside of TX)
* What do you think we need to do to improve?
* What keeps you motivated to keep working in the quarries?

=== Questions for Robert

* What draws you to research history?
* What are some good resources to research history, especially Masonic history, which can be so obscure sometimes?
* Who do you recommend for brothers to look into for research purposes, and why?
* How can researching history help a lodge?
* How do you prefer to share your research?
* What are your favorite Masonic history stories?
* Waco #92 recently digitized its minutes. Can you tell us more about that project?
** What recommendations do you have for lodges that are looking at doing that?
** Now that the project is done, what would you have done differently?
* How much digital tech do y'all use for meetings? iPads for sign-ins, computers for secretaries, stenography, etc.
* You're the brand-new secretary. What challenges are you looking at in your new role?
* What's something that you want to try doing in your lodge that you haven't tried yet?
* How can we better manage our social media presence as Masons, Lodges, and as a fraternity?
* What appendant bodies are you involved in, and do you have any cool stories, historical or otherwise, about them?
* What do you think about the idea of eBooks for ciphers and rituals?
* What's something y'all are doing in Waco #92 that you think other lodges should do?
* What's something you have seen in other lodges that you'd like to implement in Waco #92?
* Let's time-travel to the future. Your great-great-grandson is writing a history book about Masonry in that long passed era of the 2010s and 2020s. What is he writing about you, your lodge, and Texan Masonry?
* What's a jurisdiction that you'd like to learn more about?
* Are there any historical subjects where you are stuck at a dead-end? (no leads, info, etc)

More (or fewer) questions at the discretion of guest and hosts.


== _Pre-Recorded: Events for Week of Tomorrow's Release_

Brothers, it's July. That means that somewhere, near you, a lodge is having their installation of officers. Go to it! Support your local lodges. Heck, if you have travel, go support some non-local lodges! Leadership is a challenge and having people show up to welcome you into it is very reassuring. 

=== National

* https://www.reddit.com/r/freemasonry/comments/6mojj6/battleship_new_jersey_degree/?st=j51aycqe&sh=e7a1958e[July 25] - The Rough Ashlars of New Jersey are putting on a Master Mason's degree on the USS New Jersey in Camden, New Jersey. Tickets to the degree are $10 and proceeds go towards the upkeep of teh USS NJ. This event is for master masons only, and the dress code is Hawaiian shirts and slacks. Please look them up on eventbrite (E V E N T B R I T E DOT COM).

=== State

=== Local

* August 12 - Thomas B Hunter Lodge #1356 in Grand Prairie will be hosting the Julian Feild Players! The Players will be putting on the play, "A Rose Upon the Altar"  on Saturday, August 12, from 10 AM to noon. "A Rose Upon the Altar" is a play about a Lodge in 1939 that is struggling financially and trying to figure out how to keep their lodge going, and continue the chairty work that the community needs. The event is open to the public. I didn't see any admission prices, and it's listed as "free to all," but since lunch will follow the play, I would personally urge y'all to bring a little donation to help offset the costs of hospitality. 

=== Temple

* July 17 & 18 - Texas Chapter is putting on the Mark Master, Virtual Past Master, and Most Excellent Master degrees! The Mark Master degree will take place on the 17th and the VPM & MEM degrees will take place on the 18th. Both events will be in the Red Room at 6:30 PM. If you are a Royal Arch Mason, please join us!

* If you are planning on attending Brother Sam Levisee's funeral, the services will take place at 1:30 PM on this Friday the 14th of July, at the Greenwood Chapel, and interment will follow in Greenwood Memorial Park. You can find Greenwood Chapel at 3100 White Settlement Road in Fort Worth.

* As always, Fort Worth Lodge #148 meets on the second Monday of each month. Dinner is at 6 PM, and our meeting is at 7 PM. 

== Closing Thoughts on Episode Content

* Max 2 min/person, except guests.

== Quote

"http://freemasoninformation.com/2013/12/a-interview-with-arturo-dehoyos/[I believe that my role is to preserve and disseminate Masonic light and knowledge. One of the things I’ve tried to do is publish and/or write books which I wish had existed when I was a younger Mason. It was well-nigh impossible to find some of the things I’ve published when I was younger.]"
-- Illustrious Brother Arturo de Hoyos, 33° Grand Cross of Honor, Grand Archivist & Grand Historian of the Supreme Council 33° of the Ancient & Accepted Scottish Rite, Southern Jurisdiction, USA.

(Rattle off contact info for lodge, let any guests plug their websites/contact info, then sign off.)

== _Contact Info_

* _http://www.fortworth148.org/_
* _@fortworthlodge148 on Facebook_
* _info148@fortworth148.org_
* _If you live in the 64th district of the Grand Lodge of Texas and want to promote an event, please reach out to them at 64th.org - SIX FOUR TEE AITCH DOT ORG_
