= Fraternal Spotlight - Corey Harris
:published_at: 2017-06-25

== _Intro Music w/ Disclaimer_

== Host and Guest Introductions

Remember to rattle off your Blue Lodge titles, y'all.

* Rhit
* Grant
* Gabe
** "and we have a special guest today..."
* Corey

== _Masonic News for Week of Tomorrow's Release_

* To be recorded!

== Listener/Discussion Questions

* What non-principal, non-progressive line, officer role do you want to see take a bigger stage in your lodges?

== Episode Content

* Special Guest: Corey Harris

=== General Questions

These can be either "Craft" or "Life in General," if seperate answers, ask the interviewee for both.
 
* Who has been the most important or influential person to you?
** Can you tell us about them?
** How did they influence you?
* What has been your happiest moment?
* What has been your saddest moment?
* What's the most important lesson you've learned?
* What are you proudest of?
* How would you like to be remembered?
* Where did you grow up?


=== General Craft Questions

These are more specifically-oriented towards the Masonic experience of the interviewee. 

* Which Mason, living or dead, would you like to sit down and talk with for an hour?
* How would you describe yourself?
* Did you have any (maybe even many!) Masonic relatives?
** Did you have any favorites?

==== Leadship
* How does it feel to be a brand-new Worshipful Master?
** You're Arlington's youngest worshipful Master in the history of the lodge. How does _that_ feel?
** What's your list of top three, top five things to get done this year?
** Are there any ongoing or in-progress projects that you'll be continuing as worshipful master?

==== Looking Back
* What's the funniest thing that you've seen in Lodge?
* If you forgot all of your Masonic experiences except one, what would that one be?
* Is there something that you wish you'd done differently on your journey so far?
* What's something that you'd say to your past self right after your EA degree?
* Is there a time when you thought about leaving the Craft, or that Masonry was just kind of difficult to enjoy?

==== Looking Forwards
* What's on the horizon for you and your Masonic career? 
** Beyond the horizon?
* What are your hopes for what the future holds for the newest generation of Masons?
* Disregarding hopes, what are predictions (optimistic/pessimistic) for 5, 10, 20 years from now? 
* What's something you want to say to your great-great-grandson after his EA degree?

==== Regular Vocations
* Can you tell us a little about what you do for a living?
* How well does that "play" with Masonic time commitments?
* Have you had any cool run-ins with Brothers via work?
* What lessons has Masonry provided you that have been helpful to your work experience?

==== That Whole "Religion" Thin
* As a Mason, you definitely believe in some form of higher power, but can you tell us a little bit more specifically about your spiritual and/or religious beliefs?

=== AYE, LADDY
* Can you tell us about your involvement in Scottish Rite?
** In that vein, can you tell us about your experience with the knights of Saint Andrew?
** KoSA is a often cited as a great leadership experience. What lessons for KoSA are you applying, or have applied, to your Blue Lodge leadership strategies?

== _Events for Week of Tomorrow's Release_

* To be recorded!

* _As always, Fort Worth #148 meets on the Second Monday of each month, starting dinner at 6PM for a 7PM stated meeting at 1100 Henderson Street, Fort Worth, Texas_

== Closing Thoughts on Episode Content

* Max 2 min/person, except guests.

== Quote

"https://en.wikiquote.org/wiki/Theodore_Roosevelt#Quotes[There are two things that I want you to make up your minds to: first, that you are going to have a good time as long as you live – I have no use for the sour-faced man – and next, that you are going to do something worthwhile, that you are going to work hard and do the things you set out to do.]"
-- Brother President Theodor Roosevelt, in a Christmastime talk to some schoolchildren.

(Rattle off contact info for lodge, let any guests plug their websites/contact info, then sign off.)

== _Contact Info_

* _http://www.fortworth148.org/_
* _@fortworthlodge148 on Facebook_
* _info148@fortworth148.org_
* _If you live in the 64th district of the Grand Lodge of Texas and want to promote an event, please reach out to them at 64th.org - SIX FOUR TEE AITCH DOT ORG_
