= 06/22/2017 Show Notes - Quarryman's Roundtable (Special Guest: Brad Billings)
:published_at: 2017-06-21
:hp-alt-title: Podcast - Brad Billings


== _Intro Music w/ Disclaimer_

== Host and Guest Introductions

Remember to rattle off your Blue Lodge titles, y'all.

* Rhit
* Grant
* Gabe
** "and we have a special guest tonight..."
* Brad

== _Masonic News for Week of Tomorrow's Release_

In anticipation of a long episode, we will be omittting news.

== Listener/Discussion Questions

* How do you feel about lodges going dark for the summer?
* What do you think about the idea of establishing an evaluation for officers in order to give them _constructive_ advice for the next year?

== Episode Content

* Special Guest: Brad Billings
* http://texanmason.com/notes/20170621-extra-resume.html[Brad's Masonic Resume]

=== General Questions

These can be either "Craft" or "Life in General," if seperate answers, ask the interviewee for both.
 
* Who has been the most important or influential person to you?
** Can you tell us about them?
** How did they influence you?
* What has been your happiest moment?
* What has been your saddest moment?
* What's the most important lesson you've learned?
* What are you proudest of?
* How would you like to be remembered?
* Where did you grow up?


=== General Craft Questions

These are more specifically-oriented towards the Masonic experience of the interviewee. 

* Which Mason, living or dead, would you like to sit down and talk with for an hour?
* How would you describe yourself?
* Did you have any (maybe even many!) Masonic relatives?
** Did you have any favorites?

==== Leadship
* What officer positions (Blue Lodge, Grand Lodge) do you currently hold?
* You were raised in Trinity Valley Lodge #1048 and then got to be Master of the Lodge during its Centennial year. How did that feel?
** What are you most proud of accomplishing during your year in the East there?
** What's something you didn't quite get to that you'd love to see another Worshipful try and tackle?
* How are you liking this whole DDGM thing?
** What led to you becoming a DDGM?
* What led you to becoming the Grand Junior Steward, and what were your responsibilities as that Grand Officer?
* You've been a charter member and/or charter officer of a lodge, a research society, a chapel, and an assemblage.
** What are the challeges of chartering an organization?
** What was that like for you?
** Would you be interested in tackling something like that again?

==== Looking Back
* What's the funniest thing that you've seen in Lodge?
* If you forgot all of your Masonic experiences except one, what would that one be?
* Is there something that you wish you'd done differently on your journey so far?
* What's something that you'd say to your past self right after your EA degree?
* Is there a time when you thought about leaving the Craft, or that Masonry was just kind of difficult to enjoy?

==== Looking Forwards
* What's on the horizon for you and your Masonic career? 
** Beyond the horizon?
* What are your hopes for what the future holds for the newest generation of Masons?
* Disregarding hopes, what are predictions (optimistic/pessimistic) for 5, 10, 20 years from now? 
* What's something you want to say to your great-great-grandson after his EA degree?
* How do you think we can ensure that we're a sustainable organization?
* In that vein, do we really have a membership problem? 
** If we don't, what has caused that perception?
** If we do, what do you think caused it?

==== Making it Work
* What's your strategy for time management?
* What's your strategy for learning new material, and/or revisiting old material?
* What's been the most difficult thing about your level of involvement?
* Do you have any advice for younger guys who are still learning the family/vocation/Craft balance?

==== Regular Vocations
* Can you tell us a little about what you do for a living?
* How well does that "play" with Masonic time commitments?
* Have you had any cool run-ins with Brothers via work?
* What lessons has Masonry provided you that have been helpful to your work experience?

==== That Whole "Religion" Thing

* As a Mason, you definitely believe in some form of higher power, but can you tell us a little bit more specifically about your spiritual and/or religious beliefs?
* Texas requires Masons to believe in "the existence of God, the immortality of the soul, and the Divine authenticity of the Holy Scripture." Most Grand Jurisdictions require less, a small number require more. What are your thoughts on this?
* Have you ever had someone approach you with religiously-oriented (or otherwise) anti-Masonry?
** What was your response/reaction?

=== The Appendant Body Rabbit-hole

==== Just a quick dip in the water

* What current officer positions do you hold in the appendant bodies you belong to?
* What's your favorite petitionable appendant body?
* What's you favorite invitational appendant body?

==== AYE, LADDY

* Can you tell us about your experience in Scottish Rite?
* Pretend that none of the rest of us know about Scottish Rite. What's the deal with the different colored hats, and why do you wear a red one?
* What are the Knights of Saint Andrew?
* How do degree teams in Scottish Rite work?
* What do you do as a Chairman of the Ambassadors for the Membership Committee?
* What do you want to tell interested, but not yet involved, Master Masons, about Scottish Rite?

==== In the Quarries

* Can you tell us about your experience in Chapter & Council?
* How was your experience as High Priest & Thrice Illustrious Master of Love Field Chapter & Council?
* Unlike Scottish Rite, York Rite seems to be having a tough go of it and it seems to hit Chapters & Councils the hardest. What do you think is the key to revitalizing these two bodies?
* Some brothers like them, others don't; what's your opinion on Festivals?
* How has your experience as a District Deputy difference in Grand Chapter, Grand Council, and Grand Lodge?
** What led you becoming a district deputy for Chapter and district deputy for Council?
* What's the key to having an impactful year as a High Priest & Thrice Illustrious Master?
* What do you want to tell interested, but not yet involved, Master Masons, about Chapter & Council?

==== Taco Hats & Jesus

* Can you tell us about your experience in Commandery?
* How was your experience as Eminent Commander?
** Any favorite moments, events, or impacts that you made?
* How, and how well, has Commandery complimented your faith?
* Like the other bodies we've talked about, what's your Commandery elevator speech?

==== Invitational Bodies - Elevator Speech Lightining Round

* Knights of the York Cross of Honor
* Allied Masonic Degrees
* York Rite College
* Knight Masons
* The Commemorative Order of Saint Thomas of Acon
* Royal Order of Scotland
* The WSFMRMWSPPB (The Operatives)
* Holy Royal Arch Knight Templar Priests
* Societas Rosicruciana in Civitatibus Foederatis

==== Invitational Bodies - Actual Questions

* You definitely dedicated some time to AMD and are now a Past Sovereign Master. What is it about AMD that called you to leadership there?
** What has been your favorite experience in AMD?
** Is AMD intended to have a larger impact on Masonry as a whole, or is it more of a quiet preservation effort? (I'm not sure if this is the right question to ask, actually)
* You helped charter Odessa Chapel #18 for the Commemorative Order of Saint Thomas of Acon. Can you tell us some more about that?
* What's the story behind your name, Brother Alchemy, in the Royal Order of Scotland, and why do brothers pick names in the Order?
* Can you tell us more about the Worshipful Society of Free Masons, Rough Masons, Wallers, Slaters, Paviors, Plaisterers, and Bricklayers, better known as the Operatives?
** Can you tell us about chartering the San Jacinto Monument Assemblage?
* You were recently invested with the VII° Adeptus Exemptus (7th Grade, Adeptus Extremus) in the Texas College of SRICF. What does that mean in terms of responsibilites? Is that like recieving a degree for knowledge, or is that a chair degree?
** Do you have any recommendations for people who are looking to learn more about Rosicrucianism, or any book recommendations on Rosicrucian teachings?
* In your opinion, should Masonic invitational bodies be more restrictive, or less restrictive?

== _Events for Week of Tomorrow's Release_

In anticipation of a long episode, we will be omittting events.

* _As always, Fort Worth #148 meets on the Second Monday of each month, starting dinner at 6PM for a 7PM stated meeting at 1100 Henderson Street, Fort Worth, Texas_

== Closing Thoughts on Episode Content

* Max 2 min/person, except guests.

== Quote

"https://play.google.com/books/reader?id=pu45AQAAIAAJ&printsec=frontcover&output=reader&hl=en&pg=GBS.PA43[When I am employed in serving others, I do not look upon myself as conferring favors, but as paying debts. I have received much kindness from men to whom I shall never have an opportunity of making the least direct returns; and numberless mercies from God, who is infinitely above being benefited by our services. Those kindnesses from men I can, therefore, only return on their fellow-men, and I can only show my gratitude for those mercies from God by a readiness to help His other children.]"
-- Right Worshipful Brother Benjamin Franklin, May 17th entry in Poor Richard Day by Day

(Rattle off contact info for lodge, let any guests plug their websites/contact info, then sign off.)

== _Contact Info_

* _http://www.fortworth148.org/_
* _@fortworthlodge148 on Facebook_
* _info148@fortworth148.org_
* _If you live in the 64th district of the Grand Lodge of Texas and want to promote an event, please reach out to them at 64th.org - SIX FOUR TEE AITCH DOT ORG_
